//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class @case
    {
        public @case()
        {
            this.caseDoctorPrices = new HashSet<caseDoctorPrice>();
            this.transactions = new HashSet<transaction>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int defaultPrice { get; set; }
    
        public virtual ICollection<caseDoctorPrice> caseDoctorPrices { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
