//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseTransaction
    {
        public int id { get; set; }
        public int caseNumber { get; set; }
        public string caseColor1 { get; set; }
        public string caseColor2 { get; set; }
        public string caseColor3 { get; set; }
        public int price { get; set; }
        public string patientName { get; set; }
        public Nullable<System.DateTime> recieveDate { get; set; }
        public Nullable<System.DateTime> deliverDate { get; set; }
        public string notes { get; set; }
        public Nullable<bool> isOut { get; set; }
        public Nullable<bool> prova { get; set; }
        public Nullable<int> caseId { get; set; }
        public Nullable<int> doctorId { get; set; }
        public Nullable<bool> UL1 { get; set; }
        public Nullable<bool> UL2 { get; set; }
        public Nullable<bool> UL3 { get; set; }
        public Nullable<bool> UL4 { get; set; }
        public Nullable<bool> UL5 { get; set; }
        public Nullable<bool> UL6 { get; set; }
        public Nullable<bool> UL7 { get; set; }
        public Nullable<bool> UL8 { get; set; }
        public Nullable<bool> UR1 { get; set; }
        public Nullable<bool> UR2 { get; set; }
        public Nullable<bool> UR3 { get; set; }
        public Nullable<bool> UR4 { get; set; }
        public Nullable<bool> UR5 { get; set; }
        public Nullable<bool> UR6 { get; set; }
        public Nullable<bool> UR7 { get; set; }
        public Nullable<bool> UR8 { get; set; }
        public Nullable<bool> LL1 { get; set; }
        public Nullable<bool> LL2 { get; set; }
        public Nullable<bool> LL3 { get; set; }
        public Nullable<bool> LL4 { get; set; }
        public Nullable<bool> LL5 { get; set; }
        public Nullable<bool> LL6 { get; set; }
        public Nullable<bool> LL7 { get; set; }
        public Nullable<bool> LL8 { get; set; }
        public Nullable<bool> LR1 { get; set; }
        public Nullable<bool> LR2 { get; set; }
        public Nullable<bool> LR3 { get; set; }
        public Nullable<bool> LR4 { get; set; }
        public Nullable<bool> LR5 { get; set; }
        public Nullable<bool> LR6 { get; set; }
        public Nullable<bool> LR7 { get; set; }
        public Nullable<bool> LR8 { get; set; }
    
        public virtual CurrentCas CurrentCas { get; set; }
        public virtual doctor doctor { get; set; }
    }
}
