//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinicPhone
    {
        public int id { get; set; }
        public string phone { get; set; }
        public int clinicId { get; set; }
    
        public virtual clinic clinic { get; set; }
    }
}
