//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic
    {
        public clinic()
        {
            this.clinicPhones = new HashSet<clinicPhone>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int doctorId { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual ICollection<clinicPhone> clinicPhones { get; set; }
    }
}
