//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyProduct
    {
        public int id { get; set; }
        public int productId { get; set; }
        public int companyId { get; set; }
        public string unit { get; set; }
        public int quantity { get; set; }
        public int unitPrice { get; set; }
        public Nullable<System.DateTime> enterDate { get; set; }
    
        public virtual company company { get; set; }
        public virtual product product { get; set; }
    }
}
