//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentCas
    {
        public CurrentCas()
        {
            this.caseDoctorPrices = new HashSet<caseDoctorPrice>();
            this.CaseTransactions = new HashSet<CaseTransaction>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int defaultPrice { get; set; }
    
        public virtual ICollection<caseDoctorPrice> caseDoctorPrices { get; set; }
        public virtual ICollection<CaseTransaction> CaseTransactions { get; set; }
    }
}
