//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class money
    {
        public int id { get; set; }
        public bool import { get; set; }
        public int value { get; set; }
        public Nullable<System.DateTime> recieveDate { get; set; }
        public string other { get; set; }
        public string notes { get; set; }
        public Nullable<int> currentCredit { get; set; }
        public Nullable<int> doctorId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<int> companyId { get; set; }
    
        public virtual company company { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual employee employee { get; set; }
    }
}
