//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.productPays = new HashSet<productPay>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public System.DateTime enterDate { get; set; }
        public string notes { get; set; }
        public bool isFinished { get; set; }
        public Nullable<int> companyId { get; set; }
    
        public virtual company company { get; set; }
        public virtual ICollection<productPay> productPays { get; set; }
    }
}
