//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUnit
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> unitId { get; set; }
    
        public virtual product product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
