//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public string doctorName { get; set; }
        public string caseName { get; set; }
        public int caseNumber { get; set; }
        public int actualCaseNumber { get; set; }
        public string caseTeeth { get; set; }
        public string caseColor { get; set; }
        public int price { get; set; }
        public string patientName { get; set; }
        public System.DateTime recieveDate { get; set; }
        public Nullable<System.DateTime> toRecieveDate { get; set; }
        public string notes { get; set; }
        public Nullable<bool> isOut { get; set; }
        public Nullable<bool> prova { get; set; }
        public Nullable<int> caseId { get; set; }
        public Nullable<int> doctorId { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual doctor doctor { get; set; }
    }
}
