//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teethLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.ProductUnits = new HashSet<ProductUnit>();
        }
    
        public int id { get; set; }
        public string unit1 { get; set; }
    
        public virtual ICollection<ProductUnit> ProductUnits { get; set; }
    }
}
